---

name: NX1 Deploy to nonprod
run-name: Deploy to nonprod (ap-southeast-2/842675980952) by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: NX1 Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional step: Detect app and construct Dockerfile using Nixpacks
      - name: NX1 Build with Nixpacks
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'build-nixpacks'

      - name: NX1 Prepare Deployment
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'prepare'
          app_id: 9d4109f9-0808-4f37-be21-c1f65b9daa52
          api_token: 4drIOzU6Zk8JztqiSu4dUv2Uwq7B2pWThRBTydxt8cc1dce5
          env_id: e1636297-8633-4437-9636-f37402422655

      - name: NX1 Assume Role
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Service - web
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'deploy'
          service: 'web'

      # Optional step: Migrate database
      - name: NX1 Migrate Service - web
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'run'
          service: 'web'
          command: 'uname -a' # replace with your migration command


# rev:1
